/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Description: typeof import('./src/components/description.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homepage: typeof import('./src/components/Homepage.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    People: typeof import('./src/components/People.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Windows: typeof import('./src/components/Windows.vue')['default']
  }
}
