/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    Description: typeof import('./src/components/description.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homepage: typeof import('./src/components/Homepage.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    News: typeof import('./src/components/News.vue')['default']
    Outreach: typeof import('./src/components/Outreach.vue')['default']
    People: typeof import('./src/components/People.vue')['default']
    Prospective_student: typeof import('./src/components/Prospective_student.vue')['default']
    Publication: typeof import('./src/components/Publication.vue')['default']
    Research: typeof import('./src/components/Research.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teaching: typeof import('./src/components/Teaching.vue')['default']
    Windows: typeof import('./src/components/Windows.vue')['default']
  }
}
